### ISSUE TITLE
ebean.properties

### ISSUE THREAD

**Issue by hanliang1990** [ebean-orm-examples/example-minimal#2]
Hi,i user ebean with spring boot and meet some problem,do you know all param i can set in the ebean.properties file like max connection can work on? appreciate your reply.

**Comment by rbygrave** [comment]
Questions are best to go to one of:
- https://groups.google.com/forum/#!forum/ebean
- https://github.com/ebean-orm/ebean 

All the configuration is done via: https://github.com/ebean-orm/ebean/blob/master/src/main/java/io/ebean/config/ServerConfig.java ... and related classes.

> like max connection can work on

Note that if you are using Ebean's Datasource (which is recommended) then you generally don't need to tune the connection pool or change the max connections (which defaults to 200 - DataSourceConfig.java#L46). The pool trims down based on idle time to live of 5 mins (300 seconds - DataSourceConfig.java#L66)

https://github.com/ebean-orm/ebean-datasource-api/blob/master/src/main/java/io/ebean/datasource/DataSourceConfig.java#L46

https://github.com/ebean-orm/ebean-datasource-api/blob/master/src/main/java/io/ebean/datasource/DataSourceConfig.java#L66
