### ISSUE TITLE
10.1.1-SNAPSHOT

### ISSUE THREAD

**Issue by JohnBergAndersen** [ebean-orm-examples/example-minimal#3]
Maybe you should change in the pom.xml:
<artifactId>ebean</artifactId>
<version>10.1.1-SNAPSHOT</version>
to:
<artifactId>ebean</artifactId>
<version>10.1.1</version>

After that change, I could dowload the dependency. :)

**Comment by rbygrave** [comment]
Ah yes thanks.

If you want to do a little PR for that let me know.  It can be fun to dip
the toes into PR's etc.  Otherwise I'll just update it.


Thanks again, Rob.
